#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-data_objects
Version  : 0.10.16
Release  : 1
URL      : https://rubygems.org/downloads/data_objects-0.10.16.gem
Source0  : https://rubygems.org/downloads/data_objects-0.10.16.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-rdoc

%description
# data_objects
* <http://dataobjects.info>
## Description
A unified Ruby API for popular databases.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n data_objects-0.10.16
gem spec %{SOURCE0} -l --ruby > rubygem-data_objects.gemspec

%build
gem build rubygem-data_objects.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
data_objects-0.10.16.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/data_objects-0.10.16.gem
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/CustomTextType/cdesc-CustomTextType.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/CustomTextType/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/CustomTextType/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Command/cdesc-Command.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Command/connection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Command/escape_sql-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Command/execute_non_query-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Command/execute_reader-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Command/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Command/set_types-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Command/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Connection/cdesc-Connection.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Connection/concrete_command-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Connection/create_command-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Connection/driver_namespace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Connection/extension-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Connection/inherited-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Connection/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Connection/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/ConnectionError/cdesc-ConnectionError.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/DataError/cdesc-DataError.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Extension/cdesc-Extension.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Extension/connection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Extension/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/IntegrityError/cdesc-IntegrityError.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/aio%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/aio-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/buffer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/cdesc-Logger.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/delimiter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/flush-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/initialize_log-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/internal_push-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/level%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/level-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/log-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/prep_msg-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/push-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/push_closed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/push_opened-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/reset_methods-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/set_log-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logger/set_write_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logging/cdesc-Logging.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Logging/log-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/InvalidResourceError/cdesc-InvalidResourceError.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/available-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/cdesc-Pool.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/dispose-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/expired%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/flush%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/lock-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/new-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/release-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/scavenge_interval-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/used-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/Pool/wait-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/__new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/__pool_lock-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/__pool_wait-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/__pools-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/append_pool-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/cdesc-Pooling.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/detach-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/lock-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/pool_size-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/pools-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/release-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/scavenger%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/scavenger-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Pooling/scavenger_interval-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Quoting/cdesc-Quoting.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Quoting/quote_array-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Quoting/quote_boolean-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Quoting/quote_byte_array-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Quoting/quote_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Quoting/quote_date-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Quoting/quote_datetime-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Quoting/quote_numeric-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Quoting/quote_range-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Quoting/quote_regexp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Quoting/quote_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Quoting/quote_symbol-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Quoting/quote_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Quoting/quote_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Reader/cdesc-Reader.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Reader/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Reader/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Reader/field_count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Reader/fields-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Reader/next%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Reader/values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Result/affected_rows-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Result/cdesc-Result.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Result/insert_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Result/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Result/to_i-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SQLError/cdesc-SQLError.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SQLError/code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SQLError/message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SQLError/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SQLError/query-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SQLError/sqlstate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SQLError/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SQLError/uri-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SavePoint/begin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SavePoint/cdesc-SavePoint.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SavePoint/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SavePoint/commit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SavePoint/create_for_uri-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SavePoint/rollback-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Spec/PendingHelpers/cdesc-PendingHelpers.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Spec/PendingHelpers/pending_if-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Spec/cdesc-Spec.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SqlServer/cdesc-SqlServer.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/SyntaxError/cdesc-SyntaxError.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Transaction/begin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Transaction/begin_prepared-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Transaction/cdesc-Transaction.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Transaction/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Transaction/commit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Transaction/commit_prepared-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Transaction/connection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Transaction/create_for_uri-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Transaction/id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Transaction/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Transaction/not_implemented-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Transaction/prepare-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Transaction/rollback-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Transaction/rollback_prepared-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/Transaction/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/TransactionError/cdesc-TransactionError.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/cdesc-URI.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/fragment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/host-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/opaque%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/parse-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/password-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/port-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/query-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/relative%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/scheme-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/subscheme-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/URI/user-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/cdesc-DataObjects.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/exiting%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/exiting-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/full_const_get-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/DataObjects/logger-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/Extlib/ByteArray/cdesc-ByteArray.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/Extlib/cdesc-Extlib.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/MyString/cdesc-MyString.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/Object/connecting_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/Object/test_connection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/RSpec/cdesc-RSpec.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/SSLHelpers/cdesc-SSLHelpers.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/SSLHelpers/query-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/StringWithExtraPowers/cdesc-StringWithExtraPowers.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/data_objects-0.10.16/ri/page-README_markdown.ri
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/ChangeLog.markdown
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/README.markdown
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/byte_array.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/command.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/connection.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/error.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/error/connection_error.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/error/data_error.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/error/integrity_error.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/error/sql_error.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/error/syntax_error.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/error/transaction_error.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/extension.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/logger.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/pooling.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/quoting.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/reader.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/result.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/lib/pending_helpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/lib/ssl.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/setup.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/command_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/connection_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/encoding_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/error/sql_error_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/quoting_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/reader_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/result_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/typecast/array_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/typecast/bigdecimal_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/typecast/boolean_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/typecast/byte_array_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/typecast/class_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/typecast/date_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/typecast/datetime_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/typecast/float_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/typecast/integer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/typecast/ipaddr_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/typecast/nil_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/typecast/other_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/typecast/range_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/typecast/string_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/spec/shared/typecast/time_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/transaction.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/uri.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/utilities.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/lib/data_objects/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/spec/command_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/spec/connection_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/spec/do_mock.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/spec/do_mock2.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/spec/pooling_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/spec/reader_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/spec/result_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/spec/transaction_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/spec/uri_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/tasks/release.rake
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/tasks/spec.rake
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/tasks/yard.rake
/usr/lib64/ruby/gems/2.2.0/gems/data_objects-0.10.16/tasks/yardstick.rake
/usr/lib64/ruby/gems/2.2.0/specifications/data_objects-0.10.16.gemspec
