#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-data_objects
Version  : 0.10.17
Release  : 6
URL      : https://rubygems.org/downloads/data_objects-0.10.17.gem
Source0  : https://rubygems.org/downloads/data_objects-0.10.17.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-rdoc

%description
# data_objects
* <http://dataobjects.info>
## Description
A unified Ruby API for popular databases.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n data_objects-0.10.17
gem spec %{SOURCE0} -l --ruby > rubygem-data_objects.gemspec

%build
gem build rubygem-data_objects.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
data_objects-0.10.17.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/data_objects-0.10.17.gem
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/ChangeLog.markdown
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/README.markdown
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/byte_array.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/command.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/connection.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/error.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/error/connection_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/error/data_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/error/integrity_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/error/sql_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/error/syntax_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/error/transaction_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/extension.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/logger.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/pooling.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/quoting.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/reader.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/result.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/lib/pending_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/lib/ssl.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/command_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/connection_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/encoding_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/error/sql_error_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/quoting_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/reader_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/result_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/typecast/array_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/typecast/bigdecimal_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/typecast/boolean_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/typecast/byte_array_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/typecast/class_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/typecast/date_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/typecast/datetime_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/typecast/float_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/typecast/integer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/typecast/ipaddr_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/typecast/nil_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/typecast/other_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/typecast/range_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/typecast/string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/spec/shared/typecast/time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/transaction.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/uri.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/utilities.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/lib/data_objects/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/spec/command_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/spec/connection_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/spec/do_mock.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/spec/do_mock2.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/spec/pooling_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/spec/reader_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/spec/result_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/spec/transaction_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/spec/uri_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/tasks/release.rake
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/tasks/spec.rake
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/tasks/yard.rake
/usr/lib64/ruby/gems/2.3.0/gems/data_objects-0.10.17/tasks/yardstick.rake
/usr/lib64/ruby/gems/2.3.0/specifications/data_objects-0.10.17.gemspec
